-- 🎃 Halloween colorscheme for Neovim (>= 0.8)
-- Port of the VS Code theme in this repo: same palette, same token roles.
-- Install: copy this file to ~/.config/nvim/colors/halloween.lua, then :colorscheme halloween

local p = {
  bg = "#14091F", bg2 = "#0E0616", bg3 = "#1A0D2B", bg4 = "#22123A", bg5 = "#2A1245",
  bg_tabs = "#0A0510", border = "#3A1A5C",
  ghost = "#F2ECF7", bone = "#E8DCC8", candle = "#F5E6C8",
  pumpkin = "#FF7518", fill = "#B8490B", fill_dark = "#943A08",
  purple = "#B26CFF", purple_deep = "#7B2CBF", lavender = "#D9B8FF",
  slime = "#8DF56B", slime_light = "#B5FF9C", slime_dim = "#6FC753",
  candy = "#FFC93C",
  blood = "#FF2E4D", blood_deep = "#E0223B",
  teal = "#7FE0D6",
  grave = "#5E5470", whisper = "#7B6B8F", comment = "#6B5B7B", linenr = "#6B4E8F", punct = "#A897BD",
}

local function hex2rgb(h)
  h = h:gsub("#", "")
  return tonumber(h:sub(1, 2), 16), tonumber(h:sub(3, 4), 16), tonumber(h:sub(5, 6), 16)
end

-- blend(fg, bg, alpha): terminal has no alpha, so mix the colors ourselves
local function blend(fg, bg, a)
  local r1, g1, b1 = hex2rgb(fg)
  local r2, g2, b2 = hex2rgb(bg)
  local mix = function(c1, c2) return math.floor(c1 * a + c2 * (1 - a) + 0.5) end
  return string.format("#%02X%02X%02X", mix(r1, r2), mix(g1, g2), mix(b1, b2))
end

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.termguicolors = true
vim.o.background = "dark"
vim.g.colors_name = "halloween"

local hi = function(group, spec) vim.api.nvim_set_hl(0, group, spec) end
local link = function(group, target) vim.api.nvim_set_hl(0, group, { link = target }) end

-- ---------------------------------------------------------------- editor UI
hi("Normal", { fg = p.ghost, bg = p.bg })
hi("NormalNC", { fg = p.ghost, bg = p.bg })
hi("NormalFloat", { fg = p.ghost, bg = p.bg2 })
hi("FloatBorder", { fg = p.purple_deep, bg = p.bg2 })
hi("FloatTitle", { fg = p.pumpkin, bg = p.bg2, bold = true })
hi("Cursor", { fg = p.bg, bg = p.pumpkin })
hi("lCursor", { fg = p.bg, bg = p.pumpkin })
hi("TermCursor", { fg = p.bg, bg = p.pumpkin })
hi("CursorLine", { bg = p.bg4 })
hi("CursorColumn", { bg = p.bg4 })
hi("ColorColumn", { bg = p.bg4 })
hi("LineNr", { fg = p.linenr, bg = p.bg2 })
hi("LineNrAbove", { fg = p.linenr, bg = p.bg2 })
hi("LineNrBelow", { fg = p.linenr, bg = p.bg2 })
hi("CursorLineNr", { fg = p.pumpkin, bg = p.bg2, bold = true })
hi("SignColumn", { fg = p.grave, bg = p.bg2 })
hi("CursorLineSign", { bg = p.bg2 })
hi("FoldColumn", { fg = p.grave, bg = p.bg2 })
hi("CursorLineFold", { fg = p.pumpkin, bg = p.bg2 })
hi("Folded", { fg = p.whisper, bg = blend(p.purple_deep, p.bg, 0.15), italic = true })
hi("VertSplit", { fg = p.border })
hi("WinSeparator", { fg = p.border })
hi("EndOfBuffer", { fg = p.bg })
hi("NonText", { fg = p.border })
hi("Whitespace", { fg = p.border })
hi("SpecialKey", { fg = p.border })
hi("Conceal", { fg = p.whisper })
hi("Visual", { bg = blend(p.pumpkin, p.bg, 0.33) })
hi("VisualNOS", { bg = blend(p.pumpkin, p.bg, 0.2) })
hi("Search", { fg = p.ghost, bg = blend(p.pumpkin, p.bg, 0.4) })
hi("CurSearch", { fg = p.bg, bg = p.pumpkin, bold = true })
hi("IncSearch", { fg = p.bg, bg = p.pumpkin, bold = true })
hi("Substitute", { fg = p.bg, bg = p.blood })
hi("MatchParen", { fg = p.pumpkin, bg = blend(p.purple, p.bg, 0.25), bold = true, underline = true })
hi("Pmenu", { fg = p.ghost, bg = p.bg2 })
hi("PmenuSel", { fg = p.ghost, bg = p.fill })
hi("PmenuKind", { fg = p.purple, bg = p.bg2 })
hi("PmenuKindSel", { fg = p.ghost, bg = p.fill })
hi("PmenuExtra", { fg = p.whisper, bg = p.bg2 })
hi("PmenuExtraSel", { fg = p.ghost, bg = p.fill })
hi("PmenuSbar", { bg = p.bg4 })
hi("PmenuThumb", { bg = p.purple_deep })
hi("WildMenu", { fg = p.ghost, bg = p.fill })
hi("StatusLine", { fg = p.ghost, bg = p.fill })
hi("StatusLineNC", { fg = p.punct, bg = "#1E0B33" })
hi("TabLine", { fg = blend(p.ghost, p.bg_tabs, 0.55), bg = p.bg_tabs })
hi("TabLineSel", { fg = p.ghost, bg = p.bg, bold = true })
hi("TabLineFill", { bg = p.bg_tabs })
hi("WinBar", { fg = p.punct, bg = p.bg })
hi("WinBarNC", { fg = p.grave, bg = p.bg })
hi("Title", { fg = p.pumpkin, bold = true })
hi("Directory", { fg = p.candy })
hi("ErrorMsg", { fg = p.blood, bold = true })
hi("WarningMsg", { fg = p.candy })
hi("MoreMsg", { fg = p.slime })
hi("ModeMsg", { fg = p.pumpkin, bold = true })
hi("Question", { fg = p.purple })
hi("QuickFixLine", { bg = p.bg4 })
hi("qfLineNr", { fg = p.pumpkin })
hi("qfFileName", { fg = p.candy })
hi("SpellBad", { undercurl = true, sp = p.blood })
hi("SpellCap", { undercurl = true, sp = p.candy })
hi("SpellRare", { undercurl = true, sp = p.purple })
hi("SpellLocal", { undercurl = true, sp = p.teal })
hi("DiffAdd", { bg = blend(p.slime, p.bg, 0.15) })
hi("DiffChange", { bg = blend(p.candy, p.bg, 0.12) })
hi("DiffDelete", { fg = blend(p.blood, p.bg, 0.5), bg = blend(p.blood, p.bg, 0.15) })
hi("DiffText", { bg = blend(p.candy, p.bg, 0.3) })
hi("diffAdded", { fg = p.slime })
hi("diffRemoved", { fg = p.blood })
hi("diffChanged", { fg = p.candy })
hi("diffFile", { fg = p.purple })
hi("diffLine", { fg = p.candy })
hi("diffIndexLine", { fg = p.whisper })
hi("healthSuccess", { fg = p.bg, bg = p.slime })
hi("healthWarning", { fg = p.bg, bg = p.candy })
hi("healthError", { fg = p.ghost, bg = p.blood_deep })

-- ------------------------------------------------------------- syntax (vim)
hi("Comment", { fg = p.comment, italic = true })
hi("SpecialComment", { fg = p.whisper, italic = true })
hi("Todo", { fg = p.candy, bg = p.bg4, bold = true })
hi("Constant", { fg = p.pumpkin })
hi("String", { fg = p.slime })
hi("Character", { fg = p.slime })
hi("Number", { fg = p.blood })
hi("Float", { fg = p.blood })
hi("Boolean", { fg = p.pumpkin, bold = true })
hi("Identifier", { fg = p.bone })
hi("Function", { fg = p.candy })
hi("Statement", { fg = p.pumpkin, bold = true })
hi("Conditional", { fg = p.pumpkin, bold = true })
hi("Repeat", { fg = p.pumpkin, bold = true })
hi("Label", { fg = p.candy })
hi("Operator", { fg = p.ghost })
hi("Keyword", { fg = p.pumpkin, bold = true })
hi("Exception", { fg = p.pumpkin, bold = true })
hi("PreProc", { fg = p.teal })
hi("Include", { fg = p.pumpkin })
hi("Define", { fg = p.teal })
hi("Macro", { fg = p.candy })
hi("PreCondit", { fg = p.teal })
hi("Type", { fg = p.purple })
hi("StorageClass", { fg = p.pumpkin })
hi("Structure", { fg = p.purple })
hi("Typedef", { fg = p.purple })
hi("Special", { fg = p.slime_light })
hi("SpecialChar", { fg = p.slime_light })
hi("Tag", { fg = p.pumpkin })
hi("Delimiter", { fg = p.punct })
hi("Debug", { fg = p.blood })
hi("Underlined", { fg = p.purple, underline = true })
hi("Ignore", { fg = p.grave })
hi("Error", { fg = p.blood, underline = true })
hi("Added", { fg = p.slime })
hi("Removed", { fg = p.blood })
hi("Changed", { fg = p.candy })

-- ---------------------------------------------------------------- treesitter
hi("@comment", { fg = p.comment, italic = true })
hi("@comment.documentation", { fg = p.whisper, italic = true })
hi("@comment.todo", { fg = p.candy, bg = p.bg4, bold = true })
hi("@comment.note", { fg = p.teal, bg = p.bg4, bold = true })
hi("@comment.warning", { fg = p.pumpkin, bg = p.bg4, bold = true })
hi("@comment.error", { fg = p.blood, bg = p.bg4, bold = true })
hi("@string", { fg = p.slime })
hi("@string.documentation", { fg = p.whisper, italic = true })
hi("@string.escape", { fg = p.slime_light })
hi("@string.regexp", { fg = p.slime_light })
hi("@string.special", { fg = p.slime_light })
hi("@string.special.url", { fg = p.purple, underline = true })
hi("@string.special.symbol", { fg = p.purple })
hi("@character", { fg = p.slime })
hi("@character.special", { fg = p.slime_light })
hi("@number", { fg = p.blood })
hi("@number.float", { fg = p.blood })
hi("@boolean", { fg = p.pumpkin, bold = true })
hi("@constant", { fg = p.pumpkin })
hi("@constant.builtin", { fg = p.pumpkin, bold = true })
hi("@constant.macro", { fg = p.candy })
hi("@variable", { fg = p.bone })
hi("@variable.builtin", { fg = p.pumpkin, italic = true })
hi("@variable.parameter", { fg = p.bone, italic = true })
hi("@variable.parameter.builtin", { fg = p.pumpkin, italic = true })
hi("@variable.member", { fg = p.candle })
hi("@property", { fg = p.candle })
hi("@field", { fg = p.candle })
hi("@function", { fg = p.candy })
hi("@function.builtin", { fg = p.lavender })
hi("@function.call", { fg = p.candy })
hi("@function.macro", { fg = p.candy })
hi("@function.method", { fg = p.candy })
hi("@function.method.call", { fg = p.candy })
hi("@constructor", { fg = p.purple })
hi("@keyword", { fg = p.pumpkin, bold = true })
hi("@keyword.function", { fg = p.pumpkin })
hi("@keyword.operator", { fg = p.pumpkin })
hi("@keyword.import", { fg = p.pumpkin })
hi("@keyword.type", { fg = p.pumpkin })
hi("@keyword.modifier", { fg = p.pumpkin })
hi("@keyword.repeat", { fg = p.pumpkin, bold = true })
hi("@keyword.return", { fg = p.pumpkin, bold = true })
hi("@keyword.exception", { fg = p.pumpkin, bold = true })
hi("@keyword.conditional", { fg = p.pumpkin, bold = true })
hi("@keyword.directive", { fg = p.teal })
hi("@keyword.directive.define", { fg = p.teal })
hi("@keyword.storage", { fg = p.pumpkin })
hi("@operator", { fg = p.ghost })
hi("@type", { fg = p.purple })
hi("@type.builtin", { fg = p.lavender, italic = true })
hi("@type.definition", { fg = p.purple })
hi("@type.qualifier", { fg = p.pumpkin })
hi("@attribute", { fg = p.candy })
hi("@attribute.builtin", { fg = p.candy })
hi("@label", { fg = p.candy })
hi("@module", { fg = p.teal })
hi("@module.builtin", { fg = p.teal })
hi("@namespace", { fg = p.teal })
hi("@punctuation.bracket", { fg = p.ghost })
hi("@punctuation.delimiter", { fg = p.punct })
hi("@punctuation.special", { fg = p.slime_light })
hi("@tag", { fg = p.pumpkin })
hi("@tag.builtin", { fg = p.pumpkin })
hi("@tag.attribute", { fg = p.purple })
hi("@tag.delimiter", { fg = p.comment })
hi("@markup.heading", { fg = p.pumpkin, bold = true })
hi("@markup.heading.1", { fg = p.pumpkin, bold = true })
hi("@markup.heading.2", { fg = p.candy, bold = true })
hi("@markup.heading.3", { fg = p.purple, bold = true })
hi("@markup.heading.4", { fg = p.slime, bold = true })
hi("@markup.heading.5", { fg = p.teal, bold = true })
hi("@markup.heading.6", { fg = p.lavender, bold = true })
hi("@markup.strong", { fg = p.ghost, bold = true })
hi("@markup.italic", { fg = p.bone, italic = true })
hi("@markup.strikethrough", { fg = p.blood, strikethrough = true })
hi("@markup.underline", { underline = true })
hi("@markup.link", { fg = p.purple })
hi("@markup.link.label", { fg = p.purple })
hi("@markup.link.url", { fg = p.purple, underline = true })
hi("@markup.raw", { fg = p.slime })
hi("@markup.raw.block", { fg = p.slime })
hi("@markup.quote", { fg = p.whisper, italic = true })
hi("@markup.list", { fg = p.pumpkin })
hi("@markup.list.checked", { fg = p.slime })
hi("@markup.list.unchecked", { fg = p.grave })
hi("@markup.math", { fg = p.lavender })
hi("@diff.plus", { fg = p.slime })
hi("@diff.minus", { fg = p.blood })
hi("@diff.delta", { fg = p.candy })
hi("@none", {})
-- language tweaks
hi("@property.json", { fg = p.lavender })
hi("@label.json", { fg = p.lavender })
hi("@property.yaml", { fg = p.pumpkin })
hi("@property.toml", { fg = p.pumpkin })
hi("@property.css", { fg = p.slime })
hi("@tag.css", { fg = p.slime })
hi("@type.css", { fg = p.pumpkin })
hi("@number.css", { fg = p.candy })
hi("@string.css", { fg = p.candy })
hi("@keyword.sql", { fg = p.pumpkin, bold = true })

-- ---------------------------------------------------------- LSP semantic
link("@lsp.type.class", "@type")
link("@lsp.type.struct", "@type")
link("@lsp.type.interface", "@type")
link("@lsp.type.enum", "@type")
link("@lsp.type.type", "@type")
link("@lsp.type.typeParameter", "@type.builtin")
link("@lsp.type.function", "@function")
link("@lsp.type.method", "@function.method")
link("@lsp.type.macro", "@function.macro")
link("@lsp.type.namespace", "@module")
link("@lsp.type.variable", "@variable")
link("@lsp.type.parameter", "@variable.parameter")
link("@lsp.type.property", "@property")
link("@lsp.type.enumMember", "@constant")
link("@lsp.type.keyword", "@keyword")
link("@lsp.type.decorator", "@attribute")
link("@lsp.type.selfKeyword", "@variable.builtin")
link("@lsp.type.selfParameter", "@variable.builtin")
link("@lsp.type.clsParameter", "@variable.builtin")
link("@lsp.type.builtinConstant", "@constant.builtin")
link("@lsp.type.event", "@number")
hi("@lsp.type.magicFunction", { fg = p.purple, italic = true })
hi("@lsp.type.comment", {})
hi("@lsp.mod.deprecated", { fg = p.blood, strikethrough = true })
hi("@lsp.mod.static", { underline = true })
link("@lsp.typemod.variable.readonly", "@constant")
hi("@lsp.typemod.variable.defaultLibrary", { fg = p.lavender })
link("@lsp.typemod.function.defaultLibrary", "@function.builtin")
link("@lsp.typemod.variable.global", "@constant")

-- ------------------------------------------------------------- diagnostics
hi("DiagnosticError", { fg = p.blood })
hi("DiagnosticWarn", { fg = p.candy })
hi("DiagnosticInfo", { fg = p.purple })
hi("DiagnosticHint", { fg = p.teal })
hi("DiagnosticOk", { fg = p.slime })
hi("DiagnosticUnderlineError", { undercurl = true, sp = p.blood })
hi("DiagnosticUnderlineWarn", { undercurl = true, sp = p.candy })
hi("DiagnosticUnderlineInfo", { undercurl = true, sp = p.purple })
hi("DiagnosticUnderlineHint", { undercurl = true, sp = p.teal })
hi("DiagnosticUnderlineOk", { undercurl = true, sp = p.slime })
hi("DiagnosticVirtualTextError", { fg = p.blood, bg = blend(p.blood, p.bg, 0.12) })
hi("DiagnosticVirtualTextWarn", { fg = p.candy, bg = blend(p.candy, p.bg, 0.12) })
hi("DiagnosticVirtualTextInfo", { fg = p.purple, bg = blend(p.purple, p.bg, 0.12) })
hi("DiagnosticVirtualTextHint", { fg = p.teal, bg = blend(p.teal, p.bg, 0.12) })
hi("DiagnosticVirtualTextOk", { fg = p.slime, bg = blend(p.slime, p.bg, 0.12) })
link("DiagnosticSignError", "DiagnosticError")
link("DiagnosticSignWarn", "DiagnosticWarn")
link("DiagnosticSignInfo", "DiagnosticInfo")
link("DiagnosticSignHint", "DiagnosticHint")
link("DiagnosticFloatingError", "DiagnosticError")
link("DiagnosticFloatingWarn", "DiagnosticWarn")
link("DiagnosticFloatingInfo", "DiagnosticInfo")
link("DiagnosticFloatingHint", "DiagnosticHint")
hi("DiagnosticUnnecessary", { fg = blend(p.ghost, p.bg, 0.45) })
hi("DiagnosticDeprecated", { fg = p.blood, strikethrough = true })
hi("LspReferenceText", { bg = blend(p.purple, p.bg, 0.25) })
hi("LspReferenceRead", { bg = blend(p.purple, p.bg, 0.25) })
hi("LspReferenceWrite", { bg = blend(p.pumpkin, p.bg, 0.2) })
hi("LspInlayHint", { fg = p.lavender, bg = p.bg4 })
hi("LspCodeLens", { fg = p.whisper })
hi("LspCodeLensSeparator", { fg = p.grave })
hi("LspSignatureActiveParameter", { fg = p.candy, bold = true })

-- ------------------------------------------------------------------ plugins
-- gitsigns / gitgutter
hi("GitSignsAdd", { fg = p.slime, bg = p.bg2 })
hi("GitSignsChange", { fg = p.candy, bg = p.bg2 })
hi("GitSignsDelete", { fg = p.blood, bg = p.bg2 })
hi("GitSignsUntracked", { fg = p.slime_dim, bg = p.bg2 })
hi("GitSignsCurrentLineBlame", { fg = p.whisper, italic = true })
link("GitGutterAdd", "GitSignsAdd")
link("GitGutterChange", "GitSignsChange")
link("GitGutterDelete", "GitSignsDelete")
-- telescope
hi("TelescopeNormal", { fg = p.ghost, bg = p.bg2 })
hi("TelescopeBorder", { fg = p.purple_deep, bg = p.bg2 })
hi("TelescopePromptBorder", { fg = p.pumpkin, bg = p.bg2 })
hi("TelescopePromptPrefix", { fg = p.pumpkin })
hi("TelescopePromptTitle", { fg = p.bg, bg = p.pumpkin, bold = true })
hi("TelescopeResultsTitle", { fg = p.ghost, bg = p.purple_deep, bold = true })
hi("TelescopePreviewTitle", { fg = p.bg, bg = p.slime, bold = true })
hi("TelescopeSelection", { fg = p.ghost, bg = p.bg4 })
hi("TelescopeSelectionCaret", { fg = p.pumpkin, bg = p.bg4 })
hi("TelescopeMultiSelection", { fg = p.candy, bg = p.bg4 })
hi("TelescopeMatching", { fg = p.candy, bold = true })
-- nvim-cmp
hi("CmpItemAbbr", { fg = p.ghost })
hi("CmpItemAbbrDeprecated", { fg = p.grave, strikethrough = true })
hi("CmpItemAbbrMatch", { fg = p.candy, bold = true })
hi("CmpItemAbbrMatchFuzzy", { fg = p.candy })
hi("CmpItemMenu", { fg = p.whisper, italic = true })
hi("CmpItemKindDefault", { fg = p.bone })
hi("CmpItemKindText", { fg = p.ghost })
hi("CmpItemKindFunction", { fg = p.candy })
hi("CmpItemKindMethod", { fg = p.candy })
hi("CmpItemKindConstructor", { fg = p.candy })
hi("CmpItemKindClass", { fg = p.purple })
hi("CmpItemKindInterface", { fg = p.purple })
hi("CmpItemKindStruct", { fg = p.purple })
hi("CmpItemKindEnum", { fg = p.purple })
hi("CmpItemKindTypeParameter", { fg = p.lavender })
hi("CmpItemKindVariable", { fg = p.bone })
hi("CmpItemKindField", { fg = p.candle })
hi("CmpItemKindProperty", { fg = p.candle })
hi("CmpItemKindConstant", { fg = p.pumpkin })
hi("CmpItemKindEnumMember", { fg = p.pumpkin })
hi("CmpItemKindKeyword", { fg = p.pumpkin })
hi("CmpItemKindModule", { fg = p.teal })
hi("CmpItemKindSnippet", { fg = p.lavender })
hi("CmpItemKindFile", { fg = p.bone })
hi("CmpItemKindFolder", { fg = p.candy })
hi("CmpItemKindColor", { fg = p.pumpkin })
hi("CmpItemKindEvent", { fg = p.blood })
hi("CmpItemKindOperator", { fg = p.ghost })
hi("CmpItemKindUnit", { fg = p.candy })
hi("CmpItemKindValue", { fg = p.blood })
hi("CmpItemKindReference", { fg = p.purple })
-- blink.cmp
link("BlinkCmpMenu", "Pmenu")
link("BlinkCmpMenuBorder", "FloatBorder")
link("BlinkCmpMenuSelection", "PmenuSel")
link("BlinkCmpLabelMatch", "CmpItemAbbrMatch")
link("BlinkCmpLabelDeprecated", "CmpItemAbbrDeprecated")
link("BlinkCmpDocBorder", "FloatBorder")
-- nvim-tree
hi("NvimTreeNormal", { fg = p.ghost, bg = p.bg3 })
hi("NvimTreeNormalNC", { fg = p.ghost, bg = p.bg3 })
hi("NvimTreeWinSeparator", { fg = p.border, bg = p.bg3 })
hi("NvimTreeRootFolder", { fg = p.pumpkin, bold = true })
hi("NvimTreeFolderName", { fg = p.candy })
hi("NvimTreeFolderIcon", { fg = p.candy })
hi("NvimTreeOpenedFolderName", { fg = p.candy, bold = true })
hi("NvimTreeEmptyFolderName", { fg = p.whisper })
hi("NvimTreeIndentMarker", { fg = p.grave })
hi("NvimTreeSpecialFile", { fg = p.purple })
hi("NvimTreeExecFile", { fg = p.slime })
hi("NvimTreeImageFile", { fg = p.lavender })
hi("NvimTreeSymlink", { fg = p.teal })
hi("NvimTreeGitDirty", { fg = p.candy })
hi("NvimTreeGitStaged", { fg = p.slime })
hi("NvimTreeGitNew", { fg = p.slime })
hi("NvimTreeGitDeleted", { fg = p.blood })
hi("NvimTreeGitRenamed", { fg = p.purple })
hi("NvimTreeGitIgnored", { fg = p.grave })
hi("NvimTreeCursorLine", { bg = p.bg4 })
-- neo-tree
hi("NeoTreeNormal", { fg = p.ghost, bg = p.bg3 })
hi("NeoTreeNormalNC", { fg = p.ghost, bg = p.bg3 })
hi("NeoTreeWinSeparator", { fg = p.border, bg = p.bg3 })
hi("NeoTreeRootName", { fg = p.pumpkin, bold = true })
hi("NeoTreeDirectoryName", { fg = p.candy })
hi("NeoTreeDirectoryIcon", { fg = p.candy })
hi("NeoTreeFileName", { fg = p.ghost })
hi("NeoTreeIndentMarker", { fg = p.grave })
hi("NeoTreeExpander", { fg = p.grave })
hi("NeoTreeDotfile", { fg = p.whisper })
hi("NeoTreeGitAdded", { fg = p.slime })
hi("NeoTreeGitModified", { fg = p.candy })
hi("NeoTreeGitDeleted", { fg = p.blood })
hi("NeoTreeGitUntracked", { fg = p.slime })
hi("NeoTreeGitIgnored", { fg = p.grave })
hi("NeoTreeGitConflict", { fg = p.pumpkin, bold = true })
hi("NeoTreeFloatBorder", { fg = p.purple_deep, bg = p.bg2 })
hi("NeoTreeFloatTitle", { fg = p.pumpkin, bg = p.bg2, bold = true })
hi("NeoTreeTitleBar", { fg = p.bg, bg = p.pumpkin, bold = true })
hi("NeoTreeCursorLine", { bg = p.bg4 })
-- oil.nvim
hi("OilDir", { fg = p.candy })
hi("OilDirIcon", { fg = p.candy })
hi("OilLink", { fg = p.teal })
hi("OilFile", { fg = p.ghost })
-- indent-blankline / mini.indentscope
hi("IblIndent", { fg = p.bg5 })
hi("IblWhitespace", { fg = p.bg5 })
hi("IblScope", { fg = p.purple_deep })
link("IndentBlanklineChar", "IblIndent")
link("IndentBlanklineContextChar", "IblScope")
hi("MiniIndentscopeSymbol", { fg = p.purple_deep })
-- rainbow-delimiters (mirrors the VS Code bracket pair cycle)
hi("RainbowDelimiterRed", { fg = p.pumpkin })
hi("RainbowDelimiterYellow", { fg = p.purple })
hi("RainbowDelimiterBlue", { fg = p.slime })
hi("RainbowDelimiterOrange", { fg = p.candy })
hi("RainbowDelimiterGreen", { fg = p.blood })
hi("RainbowDelimiterViolet", { fg = p.teal })
hi("RainbowDelimiterCyan", { fg = p.lavender })
-- which-key
hi("WhichKey", { fg = p.pumpkin, bold = true })
hi("WhichKeyGroup", { fg = p.purple })
hi("WhichKeyDesc", { fg = p.bone })
hi("WhichKeySeparator", { fg = p.grave })
hi("WhichKeyFloat", { bg = p.bg2 })
hi("WhichKeyBorder", { fg = p.purple_deep, bg = p.bg2 })
hi("WhichKeyValue", { fg = p.whisper })
-- lazy.nvim / mason
hi("LazyH1", { fg = p.bg, bg = p.pumpkin, bold = true })
hi("LazyH2", { fg = p.pumpkin, bold = true })
hi("LazyButton", { fg = p.ghost, bg = p.bg4 })
hi("LazyButtonActive", { fg = p.ghost, bg = p.fill, bold = true })
hi("LazySpecial", { fg = p.pumpkin })
hi("LazyProgressDone", { fg = p.slime })
hi("LazyProgressTodo", { fg = p.bg5 })
hi("LazyReasonPlugin", { fg = p.purple })
hi("LazyReasonEvent", { fg = p.candy })
hi("LazyReasonKeys", { fg = p.teal })
hi("LazyDir", { fg = p.candy })
hi("LazyUrl", { fg = p.purple, underline = true })
hi("LazyCommit", { fg = p.slime })
link("MasonHeader", "LazyH1")
link("MasonHighlight", "LazySpecial")
link("MasonHighlightBlockBold", "LazyButtonActive")
link("MasonMutedBlock", "LazyButton")
-- nvim-notify
hi("NotifyERRORBorder", { fg = p.blood, bg = p.bg2 })
hi("NotifyWARNBorder", { fg = p.candy, bg = p.bg2 })
hi("NotifyINFOBorder", { fg = p.purple, bg = p.bg2 })
hi("NotifyDEBUGBorder", { fg = p.grave, bg = p.bg2 })
hi("NotifyTRACEBorder", { fg = p.lavender, bg = p.bg2 })
hi("NotifyERRORIcon", { fg = p.blood })
hi("NotifyWARNIcon", { fg = p.candy })
hi("NotifyINFOIcon", { fg = p.purple })
hi("NotifyDEBUGIcon", { fg = p.grave })
hi("NotifyTRACEIcon", { fg = p.lavender })
hi("NotifyERRORTitle", { fg = p.blood, bold = true })
hi("NotifyWARNTitle", { fg = p.candy, bold = true })
hi("NotifyINFOTitle", { fg = p.purple, bold = true })
hi("NotifyDEBUGTitle", { fg = p.grave, bold = true })
hi("NotifyTRACETitle", { fg = p.lavender, bold = true })
hi("NotifyBackground", { bg = p.bg2 })
-- noice
hi("NoiceCmdlinePopup", { fg = p.ghost, bg = p.bg2 })
hi("NoiceCmdlinePopupBorder", { fg = p.purple_deep, bg = p.bg2 })
hi("NoiceCmdlineIcon", { fg = p.pumpkin })
hi("NoiceCmdlinePopupBorderSearch", { fg = p.candy, bg = p.bg2 })
hi("NoiceCmdlineIconSearch", { fg = p.candy })
hi("NoiceMini", { fg = p.whisper, bg = p.bg3 })
-- flash / leap / hop
hi("FlashLabel", { fg = p.ghost, bg = p.blood, bold = true })
hi("FlashMatch", { bg = blend(p.purple, p.bg, 0.3) })
hi("FlashCurrent", { fg = p.bg, bg = p.pumpkin, bold = true })
hi("FlashBackdrop", { fg = p.grave })
hi("LeapLabelPrimary", { fg = p.ghost, bg = p.blood, bold = true })
hi("LeapLabelSecondary", { fg = p.bg, bg = p.candy, bold = true })
hi("LeapBackdrop", { fg = p.grave })
hi("HopNextKey", { fg = p.ghost, bg = p.blood, bold = true })
hi("HopNextKey1", { fg = p.bg, bg = p.candy, bold = true })
hi("HopNextKey2", { fg = p.candy })
hi("HopUnmatched", { fg = p.grave })
-- bufferline
hi("BufferLineFill", { bg = p.bg_tabs })
hi("BufferLineBackground", { fg = p.whisper, bg = p.bg_tabs })
hi("BufferLineBufferVisible", { fg = p.punct, bg = p.bg3 })
hi("BufferLineBufferSelected", { fg = p.ghost, bg = p.bg, bold = true })
hi("BufferLineIndicatorSelected", { fg = p.pumpkin, bg = p.bg })
hi("BufferLineIndicatorVisible", { fg = p.bg3, bg = p.bg3 })
hi("BufferLineModified", { fg = p.candy, bg = p.bg_tabs })
hi("BufferLineModifiedVisible", { fg = p.candy, bg = p.bg3 })
hi("BufferLineModifiedSelected", { fg = p.blood, bg = p.bg })
hi("BufferLineSeparator", { fg = p.bg_tabs, bg = p.bg_tabs })
hi("BufferLineSeparatorSelected", { fg = p.bg_tabs, bg = p.bg })
hi("BufferLineSeparatorVisible", { fg = p.bg_tabs, bg = p.bg3 })
hi("BufferLineCloseButtonSelected", { fg = p.blood, bg = p.bg })
hi("BufferLineTabSelected", { fg = p.pumpkin, bg = p.bg, bold = true })
-- treesitter-context
hi("TreesitterContext", { bg = p.bg3 })
hi("TreesitterContextLineNumber", { fg = p.pumpkin, bg = p.bg3 })
hi("TreesitterContextBottom", { underline = true, sp = p.border })
-- dashboard / alpha / snacks
hi("DashboardHeader", { fg = p.pumpkin })
hi("DashboardIcon", { fg = p.purple })
hi("DashboardDesc", { fg = p.bone })
hi("DashboardKey", { fg = p.candy })
hi("DashboardShortCut", { fg = p.candy })
hi("DashboardFooter", { fg = p.whisper, italic = true })
hi("AlphaHeader", { fg = p.pumpkin })
hi("AlphaButtons", { fg = p.bone })
hi("AlphaShortcut", { fg = p.candy })
hi("AlphaFooter", { fg = p.whisper, italic = true })
hi("SnacksDashboardHeader", { fg = p.pumpkin })
hi("SnacksDashboardIcon", { fg = p.purple })
hi("SnacksDashboardKey", { fg = p.candy })
hi("SnacksDashboardDesc", { fg = p.bone })
hi("SnacksDashboardFooter", { fg = p.whisper, italic = true })
hi("SnacksPickerBorder", { fg = p.purple_deep, bg = p.bg2 })
hi("SnacksPickerTitle", { fg = p.bg, bg = p.pumpkin, bold = true })
hi("SnacksPickerMatch", { fg = p.candy, bold = true })
hi("SnacksIndent", { fg = p.bg5 })
hi("SnacksIndentScope", { fg = p.purple_deep })
-- trouble
hi("TroubleNormal", { fg = p.ghost, bg = p.bg2 })
hi("TroubleText", { fg = p.bone })
hi("TroubleCount", { fg = p.bg, bg = p.pumpkin, bold = true })
hi("TroubleIndent", { fg = p.grave })
-- illuminate
link("IlluminatedWordText", "LspReferenceText")
link("IlluminatedWordRead", "LspReferenceRead")
link("IlluminatedWordWrite", "LspReferenceWrite")
-- mini.nvim bits
hi("MiniStatuslineModeNormal", { fg = p.bg, bg = p.pumpkin, bold = true })
hi("MiniStatuslineModeInsert", { fg = p.bg, bg = p.slime, bold = true })
hi("MiniStatuslineModeVisual", { fg = p.ghost, bg = p.purple_deep, bold = true })
hi("MiniStatuslineModeReplace", { fg = p.ghost, bg = p.blood_deep, bold = true })
hi("MiniStatuslineModeCommand", { fg = p.bg, bg = p.candy, bold = true })
hi("MiniStatuslineFilename", { fg = p.ghost, bg = p.bg4 })
hi("MiniStatuslineInactive", { fg = p.punct, bg = "#1E0B33" })
hi("MiniStatuslineDevinfo", { fg = p.bone, bg = p.bg5 })
hi("MiniStatuslineFileinfo", { fg = p.bone, bg = p.bg5 })
hi("MiniCursorword", { bg = blend(p.purple, p.bg, 0.25) })
hi("MiniCursorwordCurrent", { bg = blend(p.purple, p.bg, 0.25) })
hi("MiniHipatternsFixme", { fg = p.bg, bg = p.blood, bold = true })
hi("MiniHipatternsHack", { fg = p.bg, bg = p.pumpkin, bold = true })
hi("MiniHipatternsTodo", { fg = p.bg, bg = p.candy, bold = true })
hi("MiniHipatternsNote", { fg = p.bg, bg = p.teal, bold = true })
-- todo-comments.nvim
hi("TodoBgTODO", { fg = p.bg, bg = p.candy, bold = true })
hi("TodoFgTODO", { fg = p.candy })
hi("TodoBgFIX", { fg = p.ghost, bg = p.blood, bold = true })
hi("TodoFgFIX", { fg = p.blood })
hi("TodoBgHACK", { fg = p.bg, bg = p.pumpkin, bold = true })
hi("TodoFgHACK", { fg = p.pumpkin })
hi("TodoBgWARN", { fg = p.bg, bg = p.pumpkin, bold = true })
hi("TodoFgWARN", { fg = p.pumpkin })
hi("TodoBgNOTE", { fg = p.bg, bg = p.teal, bold = true })
hi("TodoFgNOTE", { fg = p.teal })
hi("TodoBgPERF", { fg = p.ghost, bg = p.purple_deep, bold = true })
hi("TodoFgPERF", { fg = p.purple })
hi("TodoBgTEST", { fg = p.bg, bg = p.slime, bold = true })
hi("TodoFgTEST", { fg = p.slime })
-- markdown (vim syntax fallbacks)
link("markdownH1", "@markup.heading.1")
link("markdownH2", "@markup.heading.2")
link("markdownH3", "@markup.heading.3")
link("markdownCode", "@markup.raw")
link("markdownCodeBlock", "@markup.raw.block")
link("markdownUrl", "@markup.link.url")
link("markdownLinkText", "@markup.link")
link("markdownBold", "@markup.strong")
link("markdownItalic", "@markup.italic")
link("markdownBlockquote", "@markup.quote")
link("markdownListMarker", "@markup.list")
-- render-markdown.nvim
hi("RenderMarkdownH1Bg", { bg = blend(p.pumpkin, p.bg, 0.15) })
hi("RenderMarkdownH2Bg", { bg = blend(p.candy, p.bg, 0.12) })
hi("RenderMarkdownH3Bg", { bg = blend(p.purple, p.bg, 0.12) })
hi("RenderMarkdownH4Bg", { bg = blend(p.slime, p.bg, 0.10) })
hi("RenderMarkdownH5Bg", { bg = blend(p.teal, p.bg, 0.10) })
hi("RenderMarkdownH6Bg", { bg = blend(p.lavender, p.bg, 0.10) })
hi("RenderMarkdownCode", { bg = p.bg2 })
hi("RenderMarkdownBullet", { fg = p.pumpkin })
hi("RenderMarkdownQuote", { fg = p.whisper, italic = true })
hi("RenderMarkdownDash", { fg = p.border })
hi("RenderMarkdownTableHead", { fg = p.pumpkin })
hi("RenderMarkdownTableRow", { fg = p.punct })

-- ----------------------------------------------------------- :terminal
vim.g.terminal_color_0 = "#2B1245"
vim.g.terminal_color_1 = p.blood_deep
vim.g.terminal_color_2 = p.slime
vim.g.terminal_color_3 = p.candy
vim.g.terminal_color_4 = "#8E6CFF"
vim.g.terminal_color_5 = "#D26CFF"
vim.g.terminal_color_6 = p.teal
vim.g.terminal_color_7 = p.bone
vim.g.terminal_color_8 = p.grave
vim.g.terminal_color_9 = p.blood
vim.g.terminal_color_10 = p.slime_light
vim.g.terminal_color_11 = "#FFDE7A"
vim.g.terminal_color_12 = p.purple
vim.g.terminal_color_13 = p.pumpkin
vim.g.terminal_color_14 = "#A8F0E8"
vim.g.terminal_color_15 = "#FFFFFF"
